spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    virtual-host: /

    listener:
      simple:
        # 采用手动应答
        acknowledge-mode: manual
        # 当前监听容器数
        concurrency: 1
        # 最大数
        max-concurrency: 1
        # 是否支持重试
        retry:
          enabled: true